
-- 1. Tabela de membros 
create table if not exists public.membros (
  id        bigint generated by default as identity primary key,
  nome      text not null,
  unidade   text not null,
  cargo     text not null default 'Desbravador',
  telefone  text,
  criado_em timestamptz not null default now()
);


-- 2. Tabela de administradores 
create table if not exists public.administradores (
  user_id   uuid primary key references auth.users (id) on delete cascade,
  email     text not null,
  criado_em timestamptz not null default now()
);

alter table public.administradores enable row level security;

-- Cada pessoa logada só enxerga a própria linha (se existir).
-- Ninguém consegue se promover a administrador pelo site: não há
-- política de insert/update/delete, então isso só é feito aqui no
-- SQL Editor ou pelo Table Editor do Supabase.
drop policy if exists "administrador ve a propria linha" on public.administradores;
create policy "administrador ve a propria linha"
  on public.administradores
  for select
  to authenticated
  using (user_id = (select auth.uid()));

revoke all on public.administradores from anon, authenticated;
grant select on public.administradores to authenticated;


-- Função usada pelas políticas e pelo site para saber se o usuário
-- logado é administrador.
create or replace function public.eh_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.administradores
    where user_id = (select auth.uid())
  );
$$;

revoke execute on function public.eh_admin() from public, anon;
grant execute on function public.eh_admin() to authenticated;


-- 3. Liga o RLS em membros e remove as políticas antigas 
alter table public.membros enable row level security;

do $$
declare
  politica record;
begin
  for politica in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'membros'
  loop
    execute format('drop policy %I on public.membros', politica.policyname);
  end loop;
end
$$;

-- Visitantes sem login não têm nenhum acesso à tabela.
revoke all on public.membros from anon;
grant select, insert, update, delete on public.membros to authenticated;


-- 4. Políticas novas: só administradores 
create policy "administradores leem membros"
  on public.membros
  for select
  to authenticated
  using ((select public.eh_admin()));

create policy "administradores cadastram membros"
  on public.membros
  for insert
  to authenticated
  with check ((select public.eh_admin()));

create policy "administradores editam membros"
  on public.membros
  for update
  to authenticated
  using ((select public.eh_admin()))
  with check ((select public.eh_admin()));

create policy "administradores excluem membros"
  on public.membros
  for delete
  to authenticated
  using ((select public.eh_admin()));
